env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - prettier
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - import
rules:
  {
    "prettier/prettier": ["error"],
    no-underscore-dangle: off,
    no-console: ["error", { allow: ["warn", "error", "info"] }],
    import/prefer-default-export: off,
    import/extensions: off,
    "@typescript-eslint/no-explicit-any": off,
    import/no-cycle: off,
    "@typescript-eslint/ban-ts-ignore": off,
    consistent-return: off,
    eslint-disable import/prefer-default-export: off,
  }
