sudo: required
services:
  - docker
before_install:
  - docker build -t tajpouria/idborm -f ./Dockerfile .
script:
  - docker run tajpouria/idborm npm run test -- --watchAll=false
branches:
  except:
    - dev 
